version: '3.8'
services:
  node_app:
    image: node:20.11.1
    container_name: my_react_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: tail -f /dev/null
